# Azure DevOps CICD Build pipeline with Noname Security Active Testing v2 shift left API Security QA Test integration

trigger:
- main

jobs:
  - job: Start_API_server
    displayName: 'Start API server to scan'
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: echo Hello API Builders and Nonamers!
        displayName: 'Hello API Builders and Nonamers'
      - script: docker run -d -p 80:80 simonkowallik/httpbin-alpine
        displayName: 'Start the API Server'

  - job: Noname_scanner
    displayName: 'Run Noname Active Scanner'
    dependsOn: Start_API_server
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          docker login \
          --username $(ACTIVE_REGISTRY_USER) \
          --password $(ACTIVE_REGISTRY_PASSWORD) jfrog.cicd.nonamesec.com/noname-docker-release
        displayName: Noname Active-cli Docker login

      - script: |
          docker run \
          --add-host=host.docker.internal:host-gateway \
          -e ACTIVE_CONFIG_FILE_PATH=https://raw.githubusercontent.com/nniryanb/build/main/active-config.json \
          -v $(pwd)/noname:/noname \
          -v $(pwd)/openapi_specs:/openapi_specs \
          --pull always \
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${ACTIVE_API_URL}/backend/version) \
          scan \
          --api-url=$(ACTIVE_API_URL) \
          --api-token=$(ACTIVE_API_TOKEN) \
          --branch-name=$(branch-name) \
          --severity-threshold=$(ACTIVE_SEVERITY_THRESHOLD) \
          --test-group-id=$(test-group-id) 
        displayName: 'run Noname active Scanner'
  
  - job: Deploy_API 
    displayName: 'Deploy API'
    dependsOn: Noname_scanner
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: echo Hello API Builders!
        displayName: 'Hello API Builders'
      - script: echo Deploy API server to production if test cases pass
        displayName: 'Deploy API server to production if test cases pass'