# Azure DevOps CICD Build pipeline with Noname Security Active Testing v2 shift left API Security QA Test integration

trigger:
- main

jobs:
  - job: Noname_scanner
    displayName: 'Run Noname Active Scanner'
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          docker login \
          --username $(ACTIVE_REGISTRY_USER)
          --password $(ACTIVE_REGISTRY_PASSWORD) jfrog.cicd.nonamesec.com/noname-docker-release
        displayName: Noname Active-cli Docker login

      - script: |
          docker run \
          --pull always \
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${ACTIVE_API_URL}/backend/version) \
          scan \
          --api-url=$(ACTIVE_API_URL) \
          --api-token=$(ACTIVE_API_TOKEN) \
          --severity-threshold=$(ACTIVE_SEVERITY_THRESHOLD) \
          --test-group-id=$(ACTIVE_APP_ID)
        displayName: 'run Noname active Scanner'
  
  - job: Deploy_API 
    displayName: 'Deploy API'
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: echo Hello API Builders!
        displayName: 'Hello API Builders'
      - script: startapiserver.sh
        displayName: 'Start the API Server if the test cases pass in the QA Test environment'