# Azure DevOps CICD Build pipeline with Noname Security Active Testing v2 shift left API Security QA Test integration
# Author @iryanb noname security 2023 All Rights Reserved. Created for Microsoft //build/ May 2023 demonstration purposes 
# configuration file to use to scan via an Azure API Manager Gateway 
# https://raw.githubusercontent.com/nniryanb/build/main/active-apimconfig.json
#
# configuration file to use to scan the api without an Azure API Manager Gateway
# -e ACTIVE_CONFIG_FILE_PATH=https://raw.githubusercontent.com/nniryanb/build/main/active-config.json

trigger:
- main

jobs:
  - job: Noname_scanner
    displayName: 'Run Noname Active Scanner'
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          docker login \
          --username $(ACTIVE_REGISTRY_USER) \
          --password $(ACTIVE_REGISTRY_PASSWORD) jfrog.cicd.nonamesec.com/noname-docker-release
        displayName: Noname Active-cli Docker login

      - script: |
          docker run \
          --add-host=host.docker.internal:host-gateway \
          -e ACTIVE_CONFIG_FILE_PATH=https://raw.githubusercontent.com/nniryanb/build/main/active-apimconfig.json \
          -v $(pwd)/noname:/noname \
          -v $(pwd)/openapi_specs:/openapi_specs \
          --pull always \
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${ACTIVE_API_URL}/backend/version) \
          scan \
          --api-url=$(ACTIVE_API_URL) \
          --api-token=$(ACTIVE_API_TOKEN) \
          --branch-name=$(branch-name) \
          --severity-threshold=$(ACTIVE_SEVERITY_THRESHOLD) \
          --test-group-id=$(test-group-id) 
        displayName: 'run Noname Active Scanner'
  
  - job: Deploy_API 
    displayName: 'Deploy API'
    dependsOn: Noname_scanner
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: echo Now you may //build/ the API server in Production fellow Nonamers!
        displayName: 'Hello API Builders and Nonamers'
      - script: echo Deploy API server to production if test cases pass
        displayName: 'Deploy API server to production if test cases pass'